
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 22 15:58:31 CST 2016
//----------------------------------------------------

package interpreteperlasintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 53;
  public static final int MASMAS = 10;
  public static final int DOSPUNTOS = 26;
  public static final int BUCLEFOREACH = 41;
  public static final int DIFERENCIA = 4;
  public static final int MENOSMENOS = 13;
  public static final int POP = 46;
  public static final int ABRIRBRACKETS = 21;
  public static final int UNSHIFT = 45;
  public static final int PUSH = 47;
  public static final int PUNTOCOMA = 25;
  public static final int CERRARLLAVES = 24;
  public static final int EQUIVALENCIA = 3;
  public static final int OROR = 8;
  public static final int LARGOLISTA = 48;
  public static final int AND = 5;
  public static final int MAYORQUE = 17;
  public static final int FUN = 31;
  public static final int OR = 7;
  public static final int ESPACIO = 52;
  public static final int CONDICIONELSE = 33;
  public static final int DIV = 14;
  public static final int ANDAND = 6;
  public static final int STRINGCOMPLEJO = 55;
  public static final int ID = 54;
  public static final int RETORNO = 42;
  public static final int EOF = 0;
  public static final int MAYORIGUALQUE = 18;
  public static final int error = 1;
  public static final int CONDICIONDEFAULT = 37;
  public static final int COMA = 27;
  public static final int MENOS = 12;
  public static final int JOIN = 50;
  public static final int BREAK = 49;
  public static final int SPLIT = 51;
  public static final int ASIGNACION = 2;
  public static final int SHIFT = 44;
  public static final int MENORQUE = 15;
  public static final int ABRIRPARENTESIS = 19;
  public static final int ABRIRLLAVES = 23;
  public static final int BUCLEFOR = 40;
  public static final int BUCLEWHILE = 38;
  public static final int CERRARBRACKETS = 22;
  public static final int CONDICIONSWITCH = 35;
  public static final int CONDICIONCASE = 36;
  public static final int MULTI = 11;
  public static final int CONDICIONIF = 32;
  public static final int MENORIGUALQUE = 16;
  public static final int BUCLEDO = 39;
  public static final int CERRARPARENTESIS = 20;
  public static final int AT = 29;
  public static final int MY = 30;
  public static final int DOLAR = 28;
  public static final int PRINT = 43;
  public static final int CONDICIONELSIF = 34;
  public static final int MAS = 9;
}

